# Generated by Django 4.0.3 on 2022-03-09 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
