# Generated by Django 4.0.3 on 2022-03-10 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0004_rename_owner_comment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['timestamp']},
        ),
    ]
