# Generated by Django 4.0.3 on 2022-03-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0005_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=350),
        ),
    ]
