# Generated by Django 4.0.3 on 2022-03-11 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main_app', '0006_alter_comment_options_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(related_name='social_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
