# Generated by Django 4.0.3 on 2022-03-14 18:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main_app', '0012_wacthlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wacthlist',
            new_name='Watchlist',
        ),
    ]
